### ISSUE TITLE
Add STRALGO command 

### ISSUE THREAD

**Issue by Terkwood** [denolib/deno-redis#101]
This command is new in Redis 6.

https://redis.io/commands/stralgo

We may want to add this to the roadmap for v1 in #78, if the desire is to support all Redis 6 features.

**Comment by braddunbar** [comment]
I'd like to take this issue if no one else is!

**Comment by Terkwood** [comment]
This is a relatively new command added in the most recent major release. uki00a will have the final say, but you're probably not going to duplicate anyone else's work if you start on it. Thank you for volunteering your time!
