### ISSUE TITLE
re-enable testSubscribe4 test

### ISSUE THREAD

**Issue by uki00a** [denolib/deno-redis#104]
## Summary

- This test case depends on `redis-server`. However, in CI, `redis-server` doesn't exist in `PATH`.
- I don't want to complicate testing in a local environment.

## Related PRs
- #103
- #92

**Comment by tumile** [comment]
I believe we can mirror how [go-redis](https://github.com/go-redis/redis/blob/master/Makefile) does it. Have Redis download and set up in a local folder, and a `startRedis` function that starts a redis-server process from fixed `redisBin` and `redisConf` path. Local testing takes longer to start, but not complicated and works universally.

https://github.com/go-redis/redis/blob/dc52593c8c63bc2a05796ec44efd317fd3e14b64/main_test.go#L278-L299

**Comment by uki00a** [comment]
Umm, this test seems to fail in my local machine... :sob:

```shell
test testSubscribe4 (#83) ... error: Uncaught Error: EOF
  if (res === null) {
          ^
    at readReply (file:///home/tanaka/projects/deno/deno-redis/io.ts:69:11)
```

@sebastienfilion Do you have any idea why?
