### ISSUE TITLE
Enforce at least one argument in commands

### ISSUE THREAD

**Issue by tumile** [denolib/deno-redis#131]
Variadic arguments are heavily used in the package. However, I think the way they are written now is quite error-prone. For example `del`
https://github.com/denolib/deno-redis/blob/4ad600278d9c6aeccbbf624eb2593d895ebb9e1c/command.ts#L50 
and most other commands require at least one argument. However, with the way the function is written above it's easy to call `del()` without any arguments, and an error is thrown. It can be instead written like this, which is semantically similar but safer.
```ts
del(key: string, ...keys: string[]): Promise<Integer>;
```

Thoughts welcome!

**Comment by Terkwood** [comment]
Seems like there's very little downside to making this change. It's a breaking change, yes, but gives a clear safety advantage.

**Comment by tumile** [comment]
Like @Terkwood said this is a breaking change to the public API so I want to hear your thoughts @uki00a before planning on implementation.

**Comment by uki00a** [comment]
I agree with this change :+1:
We haven't reached a major release yet, so I'm open to breaking changes :smile:

**Comment by uki00a** [comment]
**node-redis**

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7032a7ec67198833fcbfd18a3cc62db419e0503d/types/redis/index.d.ts#L343

**ioredis**

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7032a7ec67198833fcbfd18a3cc62db419e0503d/types/ioredis/index.d.ts#L985

**go-redis**

https://github.com/go-redis/redis/blob/3fbf7df0144b53a5c5af591df1641527c78b94e6/commands.go#L81

**Comment by uki00a** [comment]
PS) On second thought, I think the current behavior is not wrong :thinking:

## Reason 1: There may be a situation where users want to use an array

```typescript
const keys = collectKeys();
await redis.del(...keys);
```

## Reason 2: Some other clients behave the same way as this module

Fo example, go-redis and redis-cli gives the same error when no key passed:

**main.go**

```go
package main

import (
    "context"
    "fmt"
    "github.com/go-redis/redis/v8"  
)

var ctx = context.Background()

func main() {
    rdb := redis.NewClient(&redis.Options{
        Addr:     "localhost:6379",
        Password: "",
        DB:       0,
    })
    keysToDelete := []string{}
    n, err := rdb.Del(ctx, keysToDelete...).Result()
    if err != nil {
      fmt.Printf("%v\n", err)
    } else {
      fmt.Printf("%d\n", n)
    }
}
```

```shell
$ go run main.go
ERR wrong number of arguments for 'del' command
```

**Comment by tumile** [comment]
Good point. Not being able to use spread is quite painful. The error being thrown was the reason I opened this issue, I thought we could leverage type checking to protect users from themselves. But seeing that it's actually expected behavior in other packages, maybe we should follow the crowd here.
