### ISSUE TITLE
redis.executor.exec can't run redis module command JSON.GET

### ISSUE THREAD

**Issue by hkong** [denolib/deno-redis#145]
I'm trying to use `redis.executor.exec()` to run the json module (rejson).  I can verify in the redis-cli that `redis.executor.exec("JSON.SET", "rejsonObj", JSON.stringify(obj))` correctly sets `rejson` to the Object, obj.  And indeed, the return value from `redis.executor.exec()` is ["status", "OK"].

However, running `redis.executor.exec("JSON.GET", "rejsonObj"` returns `[ "rejsonObj" ] ok` instead of the object, which is what I was expecting.

According to the rejson documentation: https://oss.redislabs.com/redisjson/#python-example, the syntax I'm using should work.  Is there some way I can get the actual response message, which should be the serialized form of obj ?

Thanks in advance,

**Comment by uki00a** [comment]
@hkong Thanks for reporting this issue! I tested it with v0.13.0 and it seems to work properly:

```typescript
import { connect } from "https://deno.land/x/redis@v0.13.0/redis.ts";

const redis = await connect({ hostname: "127.0.0.1", port: 6379 });
console.log(await redis.executor.exec("JSON.SET", "rejson", ".", '{"hello": "world"}'));
console.log(await redis.executor.exec("JSON.GET", "rejson"));
```

Output:

```shell
[ "status", "OK" ]
[ "bulk", '{"hello":"world"}' ]
```

**Comment by uki00a** [comment]
@hkong Maybe this is what you want to do?

```typescript
console.log(JSON.parse(await redis.executor.exec("JSON.GET", "rejson")));
```

Current result (not expected):

```shell
error: TS2345 [ERROR]: Argument of type 'RedisRawReply' is not assignable to parameter of type 'string'.
  Type 'StatusReply' is not assignable to type 'string'.
```

Expected result:

```shell
[ "bulk", '{"hello":"world"}' ]
```

or

```shell
'{"hello":"world"}'
```

**Comment by hkong** [comment]
@uki00a Thank you so much for responding.  I tried printing the results just now using `console.dir` and you are absolutely right!.  And as you guessed, I'm parsing the wrong thing.  Parsing it this way, now gives me back the object!

```
let retval = await redis.executor.exec("JSON.GET", "rejson")
let object = console.log(JSON.parse(retval[1] as string));
```

Thank you so much for your attention!
