### ISSUE TITLE
redis uri support

### ISSUE THREAD

**Issue by oplik0** [denolib/deno-redis#153]
After searching for it in the code, it appears that this library only supports connecting to redis via hostname and port.
However, there are two uri schemes that can be used for redis connections: [redis](https://www.iana.org/assignments/uri-schemes/prov/redis) and [rediss](https://www.iana.org/assignments/uri-schemes/prov/rediss) (for connections using TLS).

These URIs look like this:
```
[redis[s]:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]
```

From my understanding, they require a bit more complicated logic than simple connect, as they actually should be equivalent to connecting and then issuing `AUTH` and/or `SELECT` commands if  password and/or database number were specified.

Main reason why I'd like to see support for this way of connecting to redis here is actually because [fly.io](https://fly.io) allows apps to easily use redis as cache ([their documentation on this](https://fly.io/docs/reference/redis/)) - but the way to connect to redis instances they host is by uri they expose as an enviromental variable. So to use this feature with deno, I'd need to parse the URI myself.

You can learn more about these schemes in IANA scheme assignment documentation:
- [redis](https://www.iana.org/assignments/uri-schemes/prov/redis)
- [rediss](https://www.iana.org/assignments/uri-schemes/prov/rediss) (for connections using TLS).

**Comment by uki00a** [comment]
@oplik0 Thanks for your suggestion! I think having support for the redis url is good :smiley: 

> From my understanding, they require a bit more complicated logic than simple connect, as they actually should be equivalent to connecting and then issuing AUTH and/or SELECT commands if password and/or database number were specified.

The `connect()` function automatically executes `AUTH` and/or `SELECT` commands if `password` and/or `db` options were specified in [RedisConnectOptions](https://doc.deno.land/https/deno.land/x/redis@v0.13.1/mod.ts#RedisConnectOptions). So I think it would be good to add a simple utility to parse the redis url as follows:

## `parseURL(url: string): RedisConnectionOptions`

```typescript
import { connect, parseURL } from "https://deno.land/x/redis/mod.ts";

const options = parseURL("redis://foo:bar@localhost:6379/1");
const redis = await connect(options);
console.log(await redis.get("key"));
```

**Comment by ralyodio** [comment]
Nevermind. I had wreong env variable name
