### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by keroxp** [denolib/deno-redis#36]
- https://redis.io/commands#stream

**Comment by Terkwood** [comment]
I've made a humble start on this effort in #86.

**Comment by Terkwood** [comment]
I haven't made it very far and will be offline for a number of days. If anyone wants to use the modest start I made in #86, I'm happy to give write access to my repository

**Comment by Terkwood** [comment]
Hi.  I'm back to work and it's proceeding very slowly.  But it is, slowly, proceeding.  :grin:

**Comment by Terkwood** [comment]
PR #86 is now ready for review!
