### ISSUE TITLE
Cluster API

### ISSUE THREAD

**Issue by keroxp** [denolib/deno-redis#37]
- https://redis.io/commands#cluster

**Comment by tumile** [comment]
Hi, I'd like to pick this up! Just opened a draft to track my progress.

**Comment by chout0000** [comment]
[nice](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/) [one](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/)

**Comment by chout0000** [comment]
[awesome](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/) [one](https://pomeranian4homepups.com/pomeranian-puppies-for-sale/)
