### ISSUE TITLE
If connection to db lost then deno process die and pup/sub not resuming.

### ISSUE THREAD

**Issue by devalexqt** [denolib/deno-redis#83]
How to handle connection (and other) DB  error? 
```

import { connect } from "https://denopkg.com/keroxp/deno-redis/mod.ts"

const redis = await connect({
  hostname: "127.0.0.1",
  port: 6379,
})

const redisSub = await connect({
    hostname: "127.0.0.1",
    port: 6379,
  })

const redisPub = await connect({
    hostname: "127.0.0.1",
    port: 6379,
})



  setInterval(async ()=>{
      console.log(new Date())
      try{
            console.log("==>redis get:",await redis.get("test"))
            await redisPub.publish("test",JSON.stringify({time:new Date()}))
      }catch(err){
          console.log("==>error:",err)
      }   
  },3000)

  var sub = await redisSub.subscribe("test")

  for await (const { channel, message } of sub.receive()) {
    console.log(">>>>>>>>>>>message from redis sub, channel:",channel,", message",message)
  }

```
Then I kill redis db process on server (emulating of problem with connections) then this app just die...
```
error: Uncaught Error: Invalid state
  throw new Error("Invalid state");
        ^
    at readLine (https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:102:9)
    at async readArrayReply (https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:141:16)
    at async RedisSubscriptionImpl.receive (https://raw.githubusercontent.com/keroxp/deno-redis/master/pubsub.ts:64:20)
    at async file:///Users/alex/Documents/Material%20Design%20Web/webserver/test_deno.js:85:39
```

And if use try/catch, after I restart DB on server, redis.get, pub, sub not resume connection and not working.

```
  try{
  var sub = await redisSub.subscribe("test")

  for await (const { channel, message } of sub.receive()) {
    console.log(">>>>>>>>>>>message from redis sub, channel:",channel,", message",message)
  }
}catch(err){console.log("==>sub error:",err)}
```
```
==>error: BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std@v0.51.0/io/bufio.ts:475:25)
    at async sendCommand (https://raw.githubusercontent.com/keroxp/deno-redis/master/io.ts:62:3)
```

So how to handle pub/sub error and resume connection and working state?

**Comment by devalexqt** [comment]
Any news?

**Comment by Terkwood** [comment]
Nicely documented! I think the next step here is for another person to reproduce this(probably not so hard), and make a suggestion on how to improve it.

**Comment by sebastienfilion** [comment]
As a first step, I created a test to reproduce the issue that @devalexqt reported. If it makes sense, I can look into suggesting a fix. https://github.com/keroxp/deno-redis/pull/91

**Comment by uki00a** [comment]
## Problem

I think the problem is that **once connection is lost, the subscriber never resumes**.

## Solutions

To resolve the above problem, I think that `deno-redis` should do the following things:

- provide a way to reconnect the lost connection.
- resume (all?) subscribers when reconnected.

## What about the other libraries?

**[ioredis](https://github.com/luin/ioredis/blob/master/API.md)** provides the auto-reconnect and auto-resubscribe features:

```javascript
new Redis({
  maxRetriesPerRequest: 5,
  autoResubscribe: true, // When reconnected, the subscriber will also resume.
  retryStrategy: times => computeNextTimeout(times),
});
```

**[go-redis](https://github.com/go-redis/redis)**

> PubSub automatically reconnects to Redis Server and resubscribes to the channels in case of network errors.

https://pkg.go.dev/github.com/go-redis/redis@v6.15.8+incompatible?tab=doc#PubSub

**Comment by uki00a** [comment]
@devalexqt @Terkwood @sebastienfilion I'm sorry for the delay response.
I've organized my thoughts.
If you have any other good ideas, please leave comments! :smile:

**Comment by Terkwood** [comment]
I vote to resume all subscribers when reconnected.

If others like the idea of auto-reconnect, that sounds good to me, too.

**Comment by sebastienfilion** [comment]
@Terkwood that was my idea. I’ve been working on a solution for the past few days; finishing testing. I hope I can push tomorrow for you all to see.
